// GENERATED by scripts/art/spriteMetrics.mjs — do not edit by hand.
//
// Where the car sits inside its 1008x1008 master. See the script header for
// why the renderer needs this: the masters carry uneven padding, so without
// it cars render at different apparent scales and the brake lights drift off
// the back of the sprite.

export interface SpriteMetric {
  /** opaque height as a fraction of the canvas */
  extentY: number;
  /** opaque width as a fraction of the canvas */
  extentX: number;
  /** rear edge, as a fraction of the half-height from centre */
  tail: number;
  damagedExtentY: number;
}

export const SPRITE_METRICS: Record<string, SpriteMetric> = {
  'arrow': { extentY: 0.9817, extentX: 0.9709, tail: 0.9817, damagedExtentY: 0.984 },
  'falcon': { extentY: 0.9767, extentX: 0.9655, tail: 0.9767, damagedExtentY: 0.9816 },
  'kestrel': { extentY: 0.9804, extentX: 0.9645, tail: 0.9791, damagedExtentY: 0.9801 },
  'kite': { extentY: 0.9782, extentX: 0.963, tail: 0.9782, damagedExtentY: 0.9827 },
  'phantom': { extentY: 0.9772, extentX: 0.9678, tail: 0.9772, damagedExtentY: 0.9824 },
  'serval': { extentY: 0.9773, extentX: 0.9717, tail: 0.9773, damagedExtentY: 0.9802 },
  'taro': { extentY: 0.9824, extentX: 0.9679, tail: 0.9835, damagedExtentY: 0.9828 },
  'vulpe': { extentY: 0.9818, extentX: 0.9691, tail: 0.983, damagedExtentY: 0.9826 },
};

/** Mean opaque height, used to normalise every car to one physical scale. */
export const REFERENCE_EXTENT_Y =
  0.9795;
