// GENERATED by scripts/art/spriteMetrics.mjs — do not edit by hand.
//
// Where the car sits inside its 1008x1008 master. See the script header for
// why the renderer needs this: the masters carry uneven padding, so without
// it cars render at different apparent scales and the brake lights drift off
// the back of the sprite.

export interface SpriteMetric {
  /** opaque height as a fraction of the canvas */
  extentY: number;
  /** opaque width as a fraction of the canvas */
  extentX: number;
  /** rear edge, as a fraction of the half-height from centre */
  tail: number;
  damagedExtentY: number;
}

export const SPRITE_METRICS: Record<string, SpriteMetric> = {
  'arrow': { extentY: 0.8611, extentX: 0.5169, tail: 0.8214, damagedExtentY: 0.8403 },
  'falcon': { extentY: 0.8661, extentX: 0.5188, tail: 0.8631, damagedExtentY: 0.8681 },
  'kestrel': { extentY: 0.88, extentX: 0.494, tail: 0.8869, damagedExtentY: 0.9246 },
  'kite': { extentY: 0.9127, extentX: 0.495, tail: 0.8889, damagedExtentY: 0.9127 },
  'phantom': { extentY: 0.9256, extentX: 0.502, tail: 0.9246, damagedExtentY: 0.9296 },
  'serval': { extentY: 0.9454, extentX: 0.4881, tail: 0.9484, damagedExtentY: 0.871 },
  'taro': { extentY: 0.9028, extentX: 0.4167, tail: 0.9087, damagedExtentY: 0.9058 },
  'vulpe': { extentY: 0.8423, extentX: 0.4673, tail: 0.8353, damagedExtentY: 0.8879 },
};

/** Mean opaque height, used to normalise every car to one physical scale. */
export const REFERENCE_EXTENT_Y =
  0.8920;
