// Prepares the top-down race sprites for the size they are actually drawn at.
//
// The top-downs generated by Kontext are photoreal studio renders, which is
// right for coherence with the studio art and wrong for a 30px sprite on a
// green field. Side by side with the cel-shaded sprites they replace, the raw
// renders read *worse* at game size: paler, lower contrast, and smaller in
// frame because the model leaves a lot of air around the car.
//
// That is not an argument for going back to cel shading — it is an argument
// for finishing the asset. Soft studio lighting and a wide frame are exactly
// what downscaling punishes, and both are cheap to fix deterministically:
//
//   1. trim to the opaque bounding box, so the car fills the sprite instead of
//      the whitespace around it (this also removes the padding variance that
//      spriteMetrics.ts exists to compensate for)
//   2. lift saturation and contrast, to put back what a 30x downscale takes out
//
//   node scripts/art/spritePrep.mjs [dir] [--dry]

import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const dir = process.argv[2] ?? 'art-review/views';
const DRY = process.argv.includes('--dry');

/** only the in-race sprites; -side and -studio are shown large and stay as-is */
const SPRITE = /-(topdown|damaged)\.png$/;
const PAD = 8;

const files = readdirSync(dir).filter((f) => SPRITE.test(f)).sort();
if (!files.length) {
  console.error(`no top-down or damaged sprites in ${dir}`);
  process.exit(1);
}

for (const name of files) {
  const file = join(dir, name);
  const { data, info } = await sharp(file).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;

  // alpha > 40 rather than > 0: the background removal leaves a faint halo of
  // near-transparent pixels, and trimming to those would keep the whitespace
  let x0 = width, y0 = height, x1 = -1, y1 = -1;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * channels + channels - 1] > 40) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  if (x1 < 0) {
    console.log(`  ${name.padEnd(24)} fully transparent — skipped`);
    continue;
  }

  const left = Math.max(0, x0 - PAD);
  const top = Math.max(0, y0 - PAD);
  const w = Math.min(width - left, x1 - x0 + 1 + PAD * 2);
  const h = Math.min(height - top, y1 - y0 + 1 + PAD * 2);
  const fill = ((x1 - x0 + 1) * (y1 - y0 + 1)) / (width * height);

  console.log(
    `  ${name.padEnd(24)} ${width}x${height} → ${w}x${h}  (car filled ${(100 * fill).toFixed(0)}% of the frame)`,
  );
  if (DRY) continue;

  const out = await sharp(file)
    .extract({ left, top, width: w, height: h })
    .modulate({ saturation: 1.35, brightness: 1.06 })
    .linear(1.18, -14)
    .png({ compressionLevel: 9 })
    .toBuffer();
  writeFileSync(file, out);
}

console.log(`\n${DRY ? 'would prepare' : 'prepared'} ${files.length} sprites`);
