// Measures where the car actually is inside its sprite, and writes the result
// out for the renderer to use.
//
// Every generated car master is a 1008x1008 square, and the car inside it runs
// anywhere from 849 to 953 pixels tall depending on which roll of the model
// produced it. The renderer maps the whole square to a fixed on-screen box, so
// that padding difference showed up as a 12% difference in apparent car size
// between machines that are supposed to be comparable — and the brake-light
// bar, positioned at a fixed fraction of the square, landed on the bumper of
// one car and in empty air behind another.
//
// Rather than re-cut 32 masters (and lose the ability to regenerate them from
// the manifests), this measures them and lets the renderer compensate.
//
//   node scripts/art/spriteMetrics.mjs

import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const DIR = 'public/assets/cars';
const OUT = 'src/render/spriteMetrics.ts';

const files = readdirSync(DIR).filter((f) => /-(topdown|damaged)\.png$/.test(f));
const metrics = {};

for (const file of files.sort()) {
  const { data, info } = await sharp(join(DIR, file))
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;
  let x0 = width, y0 = height, x1 = -1, y1 = -1;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * channels + channels - 1] > 16) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  if (x1 < 0) continue;
  const id = file.replace(/-(topdown|damaged)\.png$/, '');
  const variant = file.includes('-damaged') ? 'damaged' : 'topdown';
  metrics[id] ??= {};
  // fraction of the canvas the car occupies along each axis, and how far the
  // tail sits from centre as a fraction of the half-height
  metrics[id][variant] = {
    extentY: +((y1 - y0 + 1) / height).toFixed(4),
    extentX: +((x1 - x0 + 1) / width).toFixed(4),
    tail: +(((y1 + 1) - height / 2) / (height / 2)).toFixed(4),
  };
}

const rows = Object.entries(metrics)
  .map(([id, v]) => {
    const t = v.topdown ?? v.damaged;
    const d = v.damaged ?? v.topdown;
    return `  '${id}': { extentY: ${t.extentY}, extentX: ${t.extentX}, tail: ${t.tail}, damagedExtentY: ${d.extentY} },`;
  })
  .join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/art/spriteMetrics.mjs — do not edit by hand.
//
// Where the car sits inside its 1008x1008 master. See the script header for
// why the renderer needs this: the masters carry uneven padding, so without
// it cars render at different apparent scales and the brake lights drift off
// the back of the sprite.

export interface SpriteMetric {
  /** opaque height as a fraction of the canvas */
  extentY: number;
  /** opaque width as a fraction of the canvas */
  extentX: number;
  /** rear edge, as a fraction of the half-height from centre */
  tail: number;
  damagedExtentY: number;
}

export const SPRITE_METRICS: Record<string, SpriteMetric> = {
${rows}
};

/** Mean opaque height, used to normalise every car to one physical scale. */
export const REFERENCE_EXTENT_Y =
  ${(Object.values(metrics).reduce((a, v) => a + (v.topdown ?? v.damaged).extentY, 0) / Object.keys(metrics).length).toFixed(4)};
`,
);

console.log(`wrote ${OUT} for ${Object.keys(metrics).length} cars`);
for (const [id, v] of Object.entries(metrics)) {
  console.log(`  ${id.padEnd(10)} extentY ${(v.topdown ?? v.damaged).extentY}  tail ${(v.topdown ?? v.damaged).tail}`);
}
